### ISSUE TITLE
Cannot find module 'chalk' ???

### ISSUE THREAD

**Issue by AaronChung** [alexm118/docker-react#1]
module.js:472
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/scripts/build.js:18:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

How to fix it?

**Comment by alexm118** [comment]
Have you done an npm install? This seems like something create-react-app uses as a dependency by default.
